account_register:
   pattern:  /register
   defaults: { _controller: AcmeAccountBundle:Account:register }

account_create:
   pattern:  /register/create
   defaults: { _controller: AcmeAccountBundle:Account:create }
   
account_activate:
   pattern:  /activation/email/{email}/code/{code}
   defaults: { _controller: AcmeAccountBundle:Account:activate }
send_gift:
   pattern:  /sendgift
   defaults: { _controller: AcmeAccountBundle:Gift:sendgift }
user_stats:
   pattern:  /stats/{user}
   defaults: { _controller: AcmeAccountBundle:Gift:userstats }
   
   
   