parameters:
#    acme_index.example.class: Acme\IndexBundle\Example

services:
#    acme_index.example:
#        class: %acme_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
